# Generated by Django 4.1 on 2022-11-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Beer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("big_kind", models.CharField(max_length=100)),
                ("kind", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("brewery", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=100)),
                ("abv", models.CharField(max_length=100)),
                ("average", models.CharField(max_length=100)),
                ("ratings", models.CharField(max_length=100)),
                ("reviews", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                ("body", models.FloatField()),
                ("sweet", models.FloatField()),
                ("fruity", models.FloatField()),
                ("hoppy", models.FloatField()),
                ("malty", models.FloatField()),
            ],
        ),
    ]
